version: '3.1'

services:
  # backend:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #   environment:
  #     PORT: '3000'
  #     JWT_APP_SECRET: localhost
  #   
  postgres:
    image: postgres:11
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: localhost
      POSTGRES_DB: localhost
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
